spring:
  config:
    activate:
      on-profile:
        - local
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
